# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        install-only: true

    - name: check release file
      run: goreleaser check
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build & Test
      run: |
        cd cli
        go mod tidy
        go build -v ./...
        go test -v ./...

    - name: Run GoReleaser
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        goreleaser release

      
